In [1]:
from __future__ import print_function
import torch

In [2]:
# 1 构造一个 5x3矩阵，不进行初始化
x = torch.empty (5, 3)

In [3]:
print (x)

tensor([[-8.7341e+25,  4.5579e-41, -8.7341e+25],
        [ 4.5579e-41,  2.6491e+23,  4.5579e-41],
        [-4.4392e+26,  4.5579e-41, -4.5065e+26],
        [ 4.5579e-41, -4.5617e+26,  4.5579e-41],
        [-4.3516e+26,  4.5579e-41, -4.3803e+26]])


In [4]:
# 2 随机初始化矩阵
x = torch.rand (5, 3)

In [5]:
print (x)

tensor([[0.0959, 0.7021, 0.1818],
        [0.1734, 0.6060, 0.4043],
        [0.5852, 0.8788, 0.0811],
        [0.5742, 0.6387, 0.8992],
        [0.6695, 0.0530, 0.1408]])


In [6]:
# 3 构造一个矩阵全为0，而且数据类型是long
x = torch.zeros (5, 3, dtype=torch.long)

In [7]:
print (x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
# 4 构造一个张量
x = torch.tensor([5.5, 3])

In [9]:
print (x)

tensor([5.5000, 3.0000])


In [10]:
# 5 创建一个tensor，并且生成一个相似结构的tensor
x = x.new_ones (5, 3, dtype = torch.double)
print (x)
x = torch.rand_like (x, dtype = torch.float64)
print (x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.4625, 0.1904, 0.5519],
        [0.2882, 0.4843, 0.9084],
        [0.5100, 0.0850, 0.9746],
        [0.0932, 0.2737, 0.8926],
        [0.5581, 0.3204, 0.0821]], dtype=torch.float64)


In [11]:
# 5 获取维度信息
x.size()

torch.Size([5, 3])

In [13]:
# 6 加法操作
y = torch.rand (5, 3)

In [14]:
y

tensor([[0.2242, 0.2589, 0.2627],
        [0.9779, 0.9012, 0.3729],
        [0.0082, 0.5171, 0.1043],
        [0.8079, 0.5328, 0.9974],
        [0.7054, 0.8643, 0.1676]])

In [15]:
print (x + y)

tensor([[0.6868, 0.4493, 0.8145],
        [1.2662, 1.3855, 1.2813],
        [0.5182, 0.6021, 1.0789],
        [0.9012, 0.8065, 1.8899],
        [1.2635, 1.1847, 0.2498]], dtype=torch.float64)


In [16]:
# 6.1 提供一个参数进行相加
result = torch.empty (5, 3)
torch.add (x, y, out = result)
print (result)

tensor([[0.6868, 0.4493, 0.8145],
        [1.2662, 1.3855, 1.2813],
        [0.5182, 0.6021, 1.0789],
        [0.9012, 0.8065, 1.8899],
        [1.2635, 1.1847, 0.2498]])


In [18]:
# 7 类似与nummpy的操作
x[:, 0]

tensor([0.4625, 0.2882, 0.5100, 0.0932, 0.5581], dtype=torch.float64)

In [19]:
x[0 , :]

tensor([0.4625, 0.1904, 0.5519], dtype=torch.float64)