In [1]:
import torch

In [2]:
# requires_grad = True ，会跟踪对tensor的所有操作
x = torch.ones(2, 2, requires_grad=True)

In [3]:
print (x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print (y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
# 每个张量都有一个 .grad_fn 属性保存着创建了张量的 Function 的引用
y.grad_fn

In [6]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
# .requires_grad_( ... ) 会改变张量的 requires_grad 标记。  默认为false
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [8]:
# 计算梯度  .backward
out.backward()
print (x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
